require("patrick.set")
require("patrick.remap")
require("patrick.packer")
require("patrick.harpoon")
require("patrick.fugitive")
require("patrick.treesitter")
require("patrick.gitsigns")
require("patrick.autosave")
